# Generated by Django 3.0.5 on 2020-05-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
        ('account', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Post')),
            ],
        ),
    ]
