# Generated by Django 3.0.5 on 2020-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
