# Generated by Django 3.0.5 on 2020-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
