# Generated by Django 3.0.5 on 2020-05-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_thanks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thanks',
            new_name='Thank',
        ),
    ]
